### ISSUE TITLE
Can I capture image and send server with sim800l

### ISSUE THREAD

**Issue by canibal1** [take-iwiw/DigitalCamera_STM32#2]
I need to capture the image and send it to the server with the sim800l gsm module. I can handle sim800l, but How can I capture images with a camera and in what way should I send them?

**Comment by iwatake2222** [comment]
I have no idea about SIM800L...
In this project I use DCMI module to capture image, but I don't think SIM800L has it.

**Comment by canibal1** [comment]
What is the data type of the image from DCMI?

**Comment by iwatake2222** [comment]
rgb565

**Comment by canibal1** [comment]
Thank you for your help :)
